Controllers/CARController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Art_Gallery.Models;

namespace Art_Gallery.Controllers
{
    public class CARController : Controller
    {
        private Art_GalleryEntities db = new Art_GalleryEntities();


        public ActionResult UserRoles()
        {
            ViewBag.User_Id = new SelectList(db.Tbl_User, "User_Id", "UserName");
            ViewBag.RoleId = new SelectList(db.Tbl_Roles, "Id", "RoleName");
            return View();
        }

        // GET: CoustomArtRequest
        public ActionResult Index()
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Admin_Login", "Admin");
            }
            return View(db.Tbl_CAR.ToList());
        }

        // GET: CoustomArtRequest/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Admin_Login", "Admin");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_CAR tbl_CAR = db.Tbl_CAR.Find(id);
            if (tbl_CAR == null)
            {
                return HttpNotFound();
            }
            return View(tbl_CAR);
        }

        // GET: CoustomArtRequest/Create
        public ActionResult ArtRequest()
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Admin_Login", "Admin");
            }
            var my= db.Tbl_UserRole.Where(ac => ac.RoleId == 101).ToList();
            Tbl_User artist = new Tbl_User();
            List<SelectListItem> artists = new List<SelectListItem>();
            foreach(var item in my)
            {
                artists.Add(new SelectListItem { Value = item.User_Id.ToString(), Text = item.Tbl_User.UserName });
            }

            ViewBag.Id = artists;
            //ViewBag.Id = new SelectList(artists, "User_Id", "UserName");
            return View();
        }

        // POST: CoustomArtRequest/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ArtRequest( Tbl_CAR tbl_CAR, HttpPostedFileBase file)
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Admin_Login", "Admin");
            }
            string pic = null;
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    pic = System.IO.Path.GetFileName(file.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Image/Art_Request/"), pic);
                    // file is uploaded
                    file.SaveAs(path);
                }
                var artistname = db.Tbl_User.Where(a => a.User_Id == tbl_CAR.Artist_Id).SingleOrDefault();
                Tbl_CAR car = new Tbl_CAR();
                car.CAR_UserName = Session["UserName"].ToString();
                car.CAR_FullName = tbl_CAR.CAR_FullName;
                car.CAR_Phone = tbl_CAR.CAR_Phone;
                car.CAR_Email = tbl_CAR.CAR_Email;
                car.CAR_Image = pic;
                car.Artist_Name = artistname.User_FirstName + "  " + artistname.User_LastName;
                car.CAR_Desc = tbl_CAR.CAR_Desc;
                car.Artist_Id = tbl_CAR.Artist_Id;
                db.Tbl_CAR.Add(car);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(tbl_CAR);
        }

        // GET: CoustomArtRequest/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Admin_Login", "Admin");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_CAR tbl_CAR = db.Tbl_CAR.Find(id);
            if (tbl_CAR == null)
            {
                return HttpNotFound();
            }
            return View(tbl_CAR);
        }

        // POST: CoustomArtRequest/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CAR_Id,CAR_UserName,CAR_FullName,IsAccepted,IsRejected,Artist_Name,CAR_Image,CAR_Desc,CAR_Email,CAR_Phone")] Tbl_CAR tbl_CAR)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_CAR).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_CAR);
        }

        // GET: CoustomArtRequest/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Admin_Login", "Admin");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_CAR tbl_CAR = db.Tbl_CAR.Find(id);
            if (tbl_CAR == null)
            {
                return HttpNotFound();
            }
            return View(tbl_CAR);
        }

        // POST: CoustomArtRequest/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tbl_CAR tbl_CAR = db.Tbl_CAR.Find(id);
            db.Tbl_CAR.Remove(tbl_CAR);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/RFController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Art_Gallery.Models;

namespace Art_Gallery.Controllers
{
    public class RFController : Controller
    {
        private Art_GalleryEntities db = new Art_GalleryEntities();

        // GET: RF
        public ActionResult Index()
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Admin_Login", "Admin");
            }
            return View(db.Tbl_Feedback.ToList());
        }

        // GET: RF/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Admin_Login", "Admin");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Feedback tbl_Feedback = db.Tbl_Feedback.Find(id);
            if (tbl_Feedback == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Feedback);
        }

        // GET: RF/Create
        public ActionResult Create()
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Admin_Login", "Admin");
            }
            return View();
        }

        // POST: RF/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "F_Id,F_Type,F_DYF,F_FirstName,F_LastName,F_Phone,F_Email,F_UserName")] Tbl_Feedback tbl_Feedback)
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Admin_Login", "Admin");
            }
            if (ModelState.IsValid)
            {
                
                db.Tbl_Feedback.Add(tbl_Feedback);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tbl_Feedback);
        }

        // GET: RF/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Admin_Login", "Admin");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Feedback tbl_Feedback = db.Tbl_Feedback.Find(id);
            if (tbl_Feedback == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Feedback);
        }

        // POST: RF/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "F_Id,F_Type,F_DYF,F_FirstName,F_LastName,F_Phone,F_Email,F_UserName")] Tbl_Feedback tbl_Feedback)
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Admin_Login", "Admin");
            }
            if (ModelState.IsValid)
            {
                db.Entry(tbl_Feedback).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_Feedback);
        }

        // GET: RF/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Admin_Login", "Admin");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Feedback tbl_Feedback = db.Tbl_Feedback.Find(id);
            if (tbl_Feedback == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Feedback);
        }

        // POST: RF/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tbl_Feedback tbl_Feedback = db.Tbl_Feedback.Find(id);
            db.Tbl_Feedback.Remove(tbl_Feedback);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Art_Gallery.Models;
using Art_Gallery.Repository;

namespace Art_Gallery.Controllers
{
    public class UserController : Controller
    {
        private Art_GalleryEntities db = new Art_GalleryEntities();
        GenericUnitOfWork _unitOfWork = new GenericUnitOfWork();



        // GET: Tbl_User
        public ActionResult Index()
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Admin_Login", "Admin");
            }


            List<Tbl_User> users = new List<Tbl_User>();
            var user = db.Tbl_UserRole.Where(a => a.RoleId == 100).ToList();
            foreach (var item in user)
            {
                Tbl_User myuser = db.Tbl_User.Where(a => a.User_Id == item.User_Id).SingleOrDefault();

                users.Add(myuser);
            }
            return View(users);
        }

        // GET: Tbl_User/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Admin_Login", "Admin");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_User tbl_User = db.Tbl_User.Find(id);
            if (tbl_User == null)
            {
                return HttpNotFound();
            }
            return View(tbl_User);
        }

        // GET: Tbl_User/Create
        public ActionResult Create()
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Admin_Login", "Admin");
            }
            return View();
        }

        // POST: Tbl_User/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "User_Id,User_Email,User_Phone,User_Password,User_Image,IsActive,UserName,User_FirstName,User_LastName")] Tbl_User tbl_User)
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Admin_Login", "Admin");
            }
            if (ModelState.IsValid)
            {
                
                tbl_User.User_Image = "~/Image/User/avatar7.png";
                db.Tbl_User.Add(tbl_User);
                db.SaveChanges();
                Tbl_UserRole role = new Tbl_UserRole();
                //Tbl_User myuser = db.Tbl_User.Where(x => x.UserName == model.UserName);

                Tbl_User myuser = db.Tbl_User.Where(x => x.UserName == tbl_User.UserName).SingleOrDefault();
                role.RoleId = 100;
                role.User_Id = Convert.ToInt32(myuser.User_Id);

                db.Tbl_UserRole.Add(role);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tbl_User);
        }

        // GET: Tbl_User/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Admin_Login", "Admin");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_User tbl_User = db.Tbl_User.Find(id);
            if (tbl_User == null)
            {
                return HttpNotFound();
            }
            return View(tbl_User);
        }

        // POST: Tbl_User/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( Tbl_User tbl_User, HttpPostedFileBase file)
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Admin_Login", "Admin");
            }
            if (ModelState.IsValid)
            {
                string pic = null;
                if (file != null)
                {
                    pic = System.IO.Path.GetFileName(file.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Image/User/"), pic);
                    // file is uploaded
                    file.SaveAs(path);
                }
                tbl_User.User_Image = "~/Image/User/"+pic;
                
                _unitOfWork.GetRepositoryInstance<Tbl_User>().Update(tbl_User);
                //db.Entry(tbl_User).State = EntityState.Modified;
                //db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_User);
        }

        // GET: Tbl_User/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Admin_Login", "Admin");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_User tbl_User = db.Tbl_User.Find(id);
            if (tbl_User == null)
            {
                return HttpNotFound();
            }
            return View(tbl_User);
        }

        // POST: Tbl_User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tbl_User tbl_User = db.Tbl_User.Find(id);
            Tbl_UserRole trole = db.Tbl_UserRole.Where(model=>model.User_Id==id).SingleOrDefault();
            db.Tbl_UserRole.Remove(trole);
            db.SaveChanges();
            db.Tbl_User.Remove(tbl_User);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!-- Bootstrap core CSS-->

    <link href="~/Style/vendor/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <!-- Custom fonts for this template-->
    <link href="~/Style/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <!-- Page level plugin CSS-->
    <link href="~/Style/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/Style/css/sb-admin.css" rel="stylesheet">
</head>
<body id="page-top" style="">
    <nav class="navbar navbar-expand navbar-dark bg-dark static-top ">
        <a class="navbar-brand mr-1" href="@Url.Action("Dashboard","Admin")">Admin Board</a>
        <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button>
        
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            @*<div class="input-group">
                <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>*@
        </form>
         
        <ul class="navbar-nav ml-auto ml-md-0">
            @*<li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <span class="badge badge-danger">9+</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </li>
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i>
                <span class="badge badge-danger">7</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </li>
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user-circle fa-fw"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">Settings</a>
                <a class="dropdown-item" href="#">Activity Log</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
            </div>
        </li>*@


            <li class="nav-item dropdown no-arrow mx-1">
                <a class="nav-link " href="@Url.Action("logout","Admin")">
                    @*return RedirectToAction("Admin_Login", "Admin");*@
                    <i class="fa fa-sign-out white"></i>
                    <span class="glyphicon glyphicon-log-out">Logout</span>
                </a>

                </li>
        </ul>
    </nav>
    <div id="wrapper" class="">
        <!-- Sidebar -->
        <ul class="sidebar navbar-nav navbar-left fixed">
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Dashboard","Admin")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","User")">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Users</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","Artist")">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Artist</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","ArtGallery")">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Art Gallery</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Art","Admin")">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Arts</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ViewCategory","Admin")">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Categories</span>
                </a>
            </li>


            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Orders","Admin")">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Orders</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("OrderDetails","Admin")">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Orders Details</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","CAR")">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Custom Art Request</span>
                </a>
            </li>





            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","Report")">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Report</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","RF")">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Feedback</span>
                </a>
            </li>



        </ul>
        <div id="content-wrapper">

            <!-- Icon Cards-->
            @RenderBody()




            <!-- /.container-fluid -->
            <!-- Sticky Footer -->
            <footer class="sticky-footer">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>&copy; @DateTime.Now.Year - Art Gallery. All right reserved.</span>
                    </div>
                </div>
            </footer>
        </div>
        <!-- /.content-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>


</body>

</html>
<!-- Bootstrap core JavaScript-->
<script src="~/Style/vendor/jquery/jquery.min.js"></script>
<script src="~/Style/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- Core plugin JavaScript-->
<script src="~/Style/vendor/jquery-easing/jquery.easing.min.js"></script>
<!-- Page level plugin JavaScript-->
<script src="~/Style/vendor/chart.js/Chart.min.js"></script>
<script src="~/Style/vendor/datatables/jquery.dataTables.js"></script>
<script src="~/Style/vendor/datatables/dataTables.bootstrap4.js"></script>
<!-- Custom scripts for all pages-->
<script src="~/Style/js/sb-admin.min.js"></script>
<!-- Demo scripts for this page-->
<script src="~/Style/js/demo/datatables-demo.js"></script>
<script src="~/Style/js/demo/chart-area-demo.js"></script>