Models/Art_Gallery.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Controllers/ArtGalleryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Art_Gallery.Models;
using Art_Gallery.Repository;

namespace Art_Gallery.Controllers
{
    public class ArtGalleryController : Controller
    {
        private Art_GalleryEntities db = new Art_GalleryEntities();
        GenericUnitOfWork _unitOfWork = new GenericUnitOfWork();



        // GET: Tbl_User
        public ActionResult Index()
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Admin_Login", "Admin");
            }


            List<Tbl_User> users = new List<Tbl_User>();
            var user = db.Tbl_UserRole.Where(a => a.RoleId == 102).ToList();
            foreach (var item in user)
            {
                Tbl_User myuser = db.Tbl_User.Where(a => a.User_Id == item.User_Id).SingleOrDefault();

                users.Add(myuser);
            }
            return View(users);
        }

        // GET: Tbl_User/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Admin_Login", "Admin");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_User tbl_User = db.Tbl_User.Find(id);
            if (tbl_User == null)
            {
                return HttpNotFound();
            }
            return View(tbl_User);
        }

        // GET: Tbl_User/Create
        public ActionResult Create()
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Admin_Login", "Admin");
            }
            return View();
        }

        // POST: Tbl_User/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "User_Id,User_Email,User_Phone,User_Password,User_Image,IsActive,UserName,User_FirstName,User_LastName")] Tbl_User tbl_User)
        {
            if (ModelState.IsValid)
            {
                tbl_User.User_Image = "~/Image/User/avatar7.png";
                db.Tbl_User.Add(tbl_User);
                db.SaveChanges();
                Tbl_UserRole role = new Tbl_UserRole();
                //Tbl_User myuser = db.Tbl_User.Where(x => x.UserName == model.UserName);

                Tbl_User myuser = db.Tbl_User.Where(x => x.UserName == tbl_User.UserName).SingleOrDefault();
                role.RoleId = 101;
                role.User_Id = Convert.ToInt32(myuser.User_Id);

                db.Tbl_UserRole.Add(role);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tbl_User);
        }

        // GET: Tbl_User/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Admin_Login", "Admin");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_User tbl_User = db.Tbl_User.Find(id);
            if (tbl_User == null)
            {
                return HttpNotFound();
            }
            return View(tbl_User);
        }

        // POST: Tbl_User/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Tbl_User tbl_User, HttpPostedFileBase file)
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Admin_Login", "Admin");
            }
            if (ModelState.IsValid)
            {
                string pic = null;
                if (file != null)
                {
                    pic = System.IO.Path.GetFileName(file.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Image/User/"), pic);
                    // file is uploaded
                    file.SaveAs(path);
                }
                tbl_User.User_Image = "~/Image/User/" + pic;

                _unitOfWork.GetRepositoryInstance<Tbl_User>().Update(tbl_User);
                return RedirectToAction("Index");
            }
            return View(tbl_User);
        }

        // GET: Tbl_User/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["Admin_Id"] == null)
            {
                return RedirectToAction("Admin_Login", "Admin");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_User tbl_User = db.Tbl_User.Find(id);
            if (tbl_User == null)
            {
                return HttpNotFound();
            }
            return View(tbl_User);
        }

        // POST: Tbl_User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tbl_User tbl_User = db.Tbl_User.Find(id);
            Tbl_UserRole trole = db.Tbl_UserRole.Where(model => model.User_Id == id).SingleOrDefault();
            db.Tbl_UserRole.Remove(trole);
            db.SaveChanges();
            db.Tbl_User.Remove(tbl_User);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/ArtGallery/Create.cshtml
@model Art_Gallery.Models.Tbl_User

@{
    ViewBag.Title = "User";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />

    <div class="form-group">
        @Html.Label("First Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.User_FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.User_FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Last Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.User_LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.User_LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("User Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.Label("Email", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.User_Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.User_Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Phone", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.User_Phone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.User_Phone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Password", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.User_Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.User_Password, "", new { @class = "text-danger" })
        </div>
    </div>

    

    <div class="form-group">
        @Html.Label("Active", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.IsActive)
                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

   


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-dark" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/ArtGallery/Delete.cshtml
@model Art_Gallery.Models.Tbl_User

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
   
    <hr />
    <dl class="dl-horizontal" style="padding-left:20px">

        <dt>
            @Html.DisplayName("UserName")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayName("First Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User_FirstName)
        </dd>

        <dt>
            @Html.DisplayName("Last Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User_LastName)
        </dd>
        <dt>
            @Html.DisplayName("Email")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User_Email)
        </dd>

        <dt>
            @Html.DisplayName("Phone")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User_Phone)
        </dd>

        <dt>
            @Html.DisplayName("Password")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User_Password)
        </dd>

        <dt>
            @Html.DisplayName("Image")
        </dt>

        <dd>
            <img src="@Url.Content(Model.User_Image)" style="height:100px;width:100px;" />
        </dd>

        <dt>
            @Html.DisplayName("Active")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>



    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-dark" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/ArtGallery/Edit.cshtml
@model Art_Gallery.Models.Tbl_User

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit Art Gallery</h2>

@using (Html.BeginForm("Edit", "ArtGallery", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.User_Id)



    <div class="form-group">
        @Html.Label("UserName", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("First Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.User_FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.User_FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Last Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.User_LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.User_LastName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Email", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.User_Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.User_Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Phone", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.User_Phone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.User_Phone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Password", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.User_Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.User_Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Image", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="file" id="file" style="width: 100%;" />
            @Html.ValidationMessageFor(model => model.User_Image, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Active", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.IsActive)
                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-dark" />
        </div>
    </div>
</div>
}

Views/ArtGallery/Index.cshtml
@model IEnumerable<Art_Gallery.Models.Tbl_User>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Art Gallery</h2>



<div class="container-fluid">
    <!-- Breadcrumbs-->

    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Art Gallery</li>

    </ol>
    <!-- DataTables Example -->
    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-table"></i>
            Feedback
            <a href="../User/Create" class="btn btn-info pull-right fa fa-plus">Add New</a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Sr. No.</th>

                            <th>Username</th>
                            
                            <th>Full Name</th>
                     
                            <th>Phone</th>
                            <th>Email</th>
                            <th>Image</th>
                            <th>Active</th>
                            <th>Password</th>

                            <th>Action</th>

                        </tr>
                    </thead>
                    @{ var counter = 0;}
                    <tbody>
                        @foreach (var item in Model)
                        {
                            counter = counter + 1;

                            <tr>
                                <td>@counter</td>
                                <td>@item.UserName</td>
                                <td>@item.User_FirstName  @item.User_LastName</td>
                                <td>@item.User_Phone</td>
                                <td>@item.User_Email</td>
                                <td><img src="@Url.Content(item.User_Image)" style="height:100px;width:100px;" /></td>

                                <td>@item.IsActive</td>

                                <td>@item.User_Password</td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.User_Id, @class = "fa fa-user-edit" }) |
                                    @Html.ActionLink("Delete", "Delete", new { id = item.User_Id })
                                </td>


                            </tr>
                        }

                    </tbody>

                    <tfoot>
                        <tr>
                            <th>Sr. No.</th>

                            <th>Username</th>

                            <th>Full Name</th>

                            <th>Phone</th>
                            <th>Email</th>
                            <th>Image</th>
                            <th>Active</th>
                            <th>Password</th>

                            <th>Action</th>
                        </tr>
                    </tfoot>
                </table>
            </div>

        </div>
    </div>
</div>